language: perl
perl:
  - 5.16
  - 5.18
  - "5.20"
before_install:
  - sudo apt-get remove postgresql-client
  - sudo apt-get install postgresql-client
  - cpanm --force Test::mysqld Test::PostgreSQL
  - cpanm -n Devel::Cover::Report::Coveralls
  - cover -delete 
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
